.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.TH "sxbg" "1" "2020-03-28" 1.0
.P
.SH NAME
.P
sxbg - set background to a colour
.P
.SH SYNOPSIS
.P
\fBsxbg\fR "#RRGGBB[AA]"
.P
.SH AUTHORS
.P
prez <prez@national.shitposting.agency>
.P
.SH SOURCE
.P
https://github.com/prez/sxbg
.P
.SH SEE ALSO
.P
\fBxwallpaper\fR(1), \fBxsetroot\fR(1)
